Read and parse the ini once EEE add docstring FFF -  XXXXX
Traceback (most recent call last):
  File "bash\bash.py", line 188, in main
    _main(opts)
  File "bash\bash.py", line 362, in _main
    app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 3981, in Init
    self.InitData(progress)
  File "bash\basher\__init__.py", line 4024, in InitData
    bosh.iniInfos.refresh(refresh_target=False)
  File "bash\bosh\__init__.py", line 1627, in refresh
    _added, _deleted, _updated = self._refresh_ini_tweaks()
  File "bash\bosh\__init__.py", line 1601, in _refresh_ini_tweaks
    oldInfo = self.factory(tweak_path)
  File "bash\bosh\__init__.py", line 1490, in ini_info_factory
    inferred_ini_type = Counter(count).most_common(1)[0][0]
IndexError: list index out of range