Move record constants out of bush WIP EEE mgef school per game?
EEE Edit bush docs - namespace brec constants - belong to game

XXX BROKEN cause I made MreHasEffects(object) but this breaks MreSpell
see below (FIXED)

Used in some of the MreRecord subclassses here - I guess I need to define
__slots__ in MI too (MI with an old style class ?)

Note I removed virtually unused params of getEffectsSummary(self):
getSpellSchool(self): to reduce globals (mgef_school and co) occurrences

Note MreHasEffects indent was broken:

Mopy/bash/game/skyrim/records.py:
for loop out of with as was return - would raise ValueError: I/O operation on closed file

Mopy/bash/game/fallout3/records.py:
Mopy/bash/game/oblivion/records.py:
return inside loop

The oblivion one broke in 52515a8ec586844d043ed636d3f260a28b969d1f

What the heck?!

-------

Child squashed:

@@ -2196,5 +2196,5 @@ def mapFids(self,record,function,save=False):
 #------------------------------------------------------------------------------
-class MreHasEffects(object):
+class MreHasEffects: #(object): # this alone doesn't break MreSpel
     """Mixin class for magic items."""
-    __slots__ = []
+    ##: __slots__ = [] # MreSpel.flags should be renamed to _flags

Revert class MreHasEffects: #(object):

Breaks MreSpel as in:

Error in Oblivion.esm
parsers.py 3994 load:
Traceback (most recent call last):
  File "bash\parsers.py", line 3988, in load
    self.tops[label].load(ins, do_unpack and (topClass != MobBase))
  File "bash\record_groups.py", line 84, in load
    ins.tell() + self.size - self.header.__class__.rec_header_size)
  File "bash\record_groups.py", line 186, in loadData
    record = recClass(header,ins,True)
  File "bash\brec.py", line 1690, in __init__
    self.__class__.melSet.initRecord(self, header, ins, do_unpack)
  File "bash\brec.py", line 1234, in initRecord
    element.setDefault(record)
  File "bash\brec.py", line 977, in setDefault
    setter(attr,value)
AttributeError: 'MreSpel' object attribute 'flags' is read-only

class MreRecord(object):
    __slots__ = []

class MreHasEffects(object): # this alone doesn't break MreSpel
    """Mixin class for magic items."""
    ##: __slots__ = [] # MreSpel.flags should be renamed to _flags

class MreSpel(MreRecord, MreHasEffects):
    flags = 'class variable'
    __slots__ = ('flags', )

    # def __init__(self, flags='instance_var'):
    #     self.flags = flags

spell = MreSpel()
print (spell.flags)
spell.flags = 'set'
spell.flags1 = 'set'
print (spell.flags)
print (spell.__class__.flags)