XXX partially revert 'XXX wip test ghosts'
Breaks renaming installers:

Traceback (most recent call last):
  File "bash\basher\__init__.pyo", line 2259, in OnLabelEdited
  File "bash\bosh\__init__.pyo", line 1155, in rename_info
  File "bash\bosh\bain.pyo", line 1688, in _rename_operation
  File "bash\bosh\bain.pyo", line 1275, in renameInstaller
  File "bash\bosh\bain.pyo", line 980, in _installer_rename
  File "bash\bosh\__init__.pyo", line 1174, in _rename_operation
  File "bash\bosh\__init__.pyo", line 1183, in _get_rename_paths
AttributeError: 'InstallerArchive' object has no attribute 'abs_path'