Wip proper handling of ini tweaks encoding EEE
Mopy/bash/bosh/bain.py -> avoid BestIniFile

+        except UnicodeDecodeError:
+            deprint(u'ini_encoding does not do the trick', traceback=True)

FFF

@@ -2001,3 +2000,3 @@ def _refresh_mod_inis(self):
                 iniPath].do_update():
-                self._plugin_inis[iniPath] = IniFile(iniPath)
+                self._plugin_inis[iniPath] = IniFile(iniPath, 'cp1252')

EEE I don't like hardcoding cp1252 here

https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=173848

Traceback (most recent call last):
  File "bash\bash.py", line 185, in main
    _main(op﻿ts)
  File "bash\bash.py", line 360, in _main
    app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 3981, in Init
    self.InitData(progress)
  File "bash\basher\__init__.py", line 4018, in InitData
    bosh.modInfos.refresh(booting=True)
  File "bash\bosh\__init__.py", line 1965, in refresh
    forceRefresh=hasChanged or _modTimesChange, forceActive=deleted)
  File "bash\bosh\__init__.py", line 1720, in _modinfos_cache_wrapper
    self._refresh_mod_inis() # before _refreshMissingStrings !
  File "bash\bosh\__init__.py", line 1998, in _refresh_mod_inis﻿
    self._plugin_inis[iniPath] = IniFile﻿(iniPath)
TypeError: __init__() takes exactly 3 arguments (2 given)